/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseBreadcrumb: typeof import('./src/components/BaseBreadcrumb.vue')['default']
    BaseBreadCrumb: typeof import('./src/components/BaseBreadCrumb.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseCarousel: typeof import('./src/components/BaseCarousel.vue')['default']
    BaseDialog: typeof import('./src/components/BaseDialog.vue')['default']
    BBreadcrumb: typeof import('bootstrap-vue-next/components/BBreadcrumb')['BBreadcrumb']
    BBreadcrumbItem: typeof import('bootstrap-vue-next/components/BBreadcrumb')['BBreadcrumbItem']
    BCarousel: typeof import('bootstrap-vue-next/components/BCarousel')['BCarousel']
    BCarouselSlide: typeof import('bootstrap-vue-next/components/BCarousel')['BCarouselSlide']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
